pipeline {
    agent any
    parameters {
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
    }
    stages {
        stage('Example Build') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Example Deploy') {
            when {
                branch 'main'
                expression { TOGGLE ==~ /true/ }
            }
            steps {
                echo 'Deploying'
            }
        }
    }
}