@Library ('shared-library')_

pipeline {
    agent any
    stages{
        stage('Build'){
            steps{
                script{
                    build()
                }
            }
        }
    }
}